INSERT INTO specializations (id, name, description, is_active, created_at, updated_at)
VALUES 
  ('f7f6a953-96f1-11f0-98cd-2e96694c4265', 'Pediatric Physiotherapy', 'Focuses on diagnosing, treating, and managing movement disorders and developmental conditions in infants, children, and adolescents.', true, NOW(), NOW()),
  ('f7f6b01f-96f1-11f0-98cd-2e96694c4265', 'Neurological Physiotherapy', 'Specializes in rehabilitation for patients with neurological disorders such as stroke, spinal cord injury, multiple sclerosis, and Parkinson’s disease.', true, NOW(), NOW()),
  ('f7f6b23a-96f1-11f0-98cd-2e96694c4265', 'Cardiopulmonary / Cardiovascular & Pulmonary Physiotherapy', 'Helps patients with heart and lung conditions including cardiac rehab, COPD, asthma, and post-surgical recovery to improve endurance and breathing.', true, NOW(), NOW()),
  ('f7f6b462-96f1-11f0-98cd-2e96694c4265', 'Orthopedic / Musculoskeletal Physiotherapy', 'Focuses on muscles, bones, ligaments, tendons, and joints; treating fractures, arthritis, post-surgery rehab, and sports or workplace injuries.', true, NOW(), NOW()),
  ('f7f6b5ee-96f1-11f0-98cd-2e96694c4265', 'Geriatric Physiotherapy', 'Supports elderly patients by addressing mobility issues, arthritis, osteoporosis, balance problems, and recovery from hip or knee replacements.', true, NOW(), NOW()),
  ('f7f6b76b-96f1-11f0-98cd-2e96694c4265', 'Sports Physiotherapy', 'Dedicated to prevention, treatment, and rehabilitation of sports injuries, enhancing performance, and safe return to physical activity for athletes.', true, NOW(), NOW()),
  ('f7f6b8f1-96f1-11f0-98cd-2e96694c4265', 'Women’s Health Physiotherapy', 'Focuses on female health including pregnancy-related pain, postnatal recovery, pelvic floor dysfunction, and management of incontinence.', true, NOW(), NOW()),
  ('f7f6ba70-96f1-11f0-98cd-2e96694c4265', 'Community Physiotherapy', 'Provides physiotherapy services in community and home settings, managing chronic illness, rehabilitation, and support for long-term disabilities.', true, NOW(), NOW()),
  ('f7f6bc0e-96f1-11f0-98cd-2e96694c4265', 'Hand Therapy', 'Specialized rehabilitation of hand, wrist, and upper limb conditions, including fractures, tendon injuries, and post-surgical recovery.', true, NOW(), NOW()),
  ('f7f6bd8d-96f1-11f0-98cd-2e96694c4265', 'Vestibular Rehabilitation', 'Helps patients with dizziness, vertigo, and balance disorders caused by inner ear problems, using exercises to improve stability and coordination.', true, NOW(), NOW()),
  ('f7f6bf11-96f1-11f0-98cd-2e96694c4265', 'Oncology Physiotherapy', 'Assists cancer patients with rehabilitation, fatigue management, pain control, lymphedema care, and improving quality of life during or after treatment.', true, NOW(), NOW()),
  ('f7f6c111-96f1-11f0-98cd-2e96694c4265', 'Intensive Care / Critical Care Physiotherapy', 'Works with ICU patients to improve breathing, mobility, circulation, and recovery for those on ventilators or after major surgery and trauma.', true, NOW(), NOW()),
  ('f7f6c28a-96f1-11f0-98cd-2e96694c4265', 'Aquatic Physiotherapy (Hydrotherapy)', 'Uses water-based therapy to reduce pain, improve strength, mobility, and rehabilitation for conditions like arthritis, injuries, and neurological issues.', true, NOW(), NOW()),
  ('f7f6c3ec-96f1-11f0-98cd-2e96694c4265', 'Pain Management Physiotherapy', 'Specializes in managing chronic pain through physiotherapy techniques, exercises, and education to improve function and overall quality of life.', true, NOW(), NOW()),
  ('f7f6c56e-96f1-11f0-98cd-2e96694c4265', 'Occupational Health Physiotherapy', 'Focuses on workplace injuries, ergonomics, posture correction, and rehabilitation to ensure safe return to work and prevention of future injuries.', true, NOW(), NOW()),
  ('f7f6c6d6-96f1-11f0-98cd-2e96694c4265', 'Palliative Care Physiotherapy', 'Supports patients with terminal or life-limiting illnesses by improving comfort, mobility, reducing pain, and enhancing quality of life.', true, NOW(), NOW()),
  ('f7f6c840-96f1-11f0-98cd-2e96694c4265', 'Animal Physiotherapy', 'Provides rehabilitation for animals, particularly pets and horses, to recover from injuries, surgeries, and mobility issues using physiotherapy methods.', true, NOW(), NOW());